# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 416c4d4e87b2fbd5cd187723c5e2b3a4401305a4214160d8781ad20ab79ebe2210d97f898495a17e69534138cb7c7f5fee51aa081f655e597e4d0e0611a861d1

test:
  secret_key_base: 25a7a48e1e580ad76111bdb4c8284c3e59beed4f3ef6dddcb18b754163c31924f3e673488cb8446bef005cf34bb27010e4a69964916094972fa83bad74ab8757

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
